// Do not edit this file directly.
// Instead, edit the `tooling/eslint/next.config.mjs` file.
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { FlatCompat } = require('@eslint/eslintrc');
const compat = new FlatCompat({
    baseDirectory: import.meta.dirname,
});

/** @type {import('eslint').Linter.Config[]} */
export default [
    ...compat.config({
        extends: ["next"],
        settings: {
            next: {
                rootDir: ".",
            },
        },
        rules: {
            // ❌ Prohíbe onClick en JSX (te fuerza a usar onPress del DS)
            "no-restricted-syntax": [
                "error",
                {
                    selector: 'JSXAttribute[name.name="onClick"]',
                    message: "Usa 'onPress' y el Button del DS (@repo/design/components/Button).",
                },
                {
                    selector: 'JSXOpeningElement[name.name="button"]',
                    message: "No uses <button> crudo. Usa @repo/design/components/Button.",
                },
            ],
        },
    }),
];
