packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@types/react': 19.0.12
  babel-jest: 29.7.0
  react: 19.0.0
  react-dom: 19.0.0
  react-native: 0.79.5
  react-native-edge-to-edge: 1.6.2
  react-native-gesture-handler: 2.26.0
  react-native-reanimated: 3.17.4
  react-native-safe-area-context: 5.5.0
  react-native-screens: 4.11.1
  react-native-webview: 13.15.0
  react-test-renderer: 19.0.0
  recharts: 2.15.4
  tailwindcss: 3.4.17

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  react: 19.0.0
  react-dom: 19.0.0
  scheduler: ^0.25.0
  lightningcss: 1.27.0
