import React from "react";
import { View } from "react-native";
type FC<P = any> = React.FC<React.PropsWithChildren<P>>;
export const DropdownMenu: FC = ({ children }) => <View>{children}</View>;
export const DropdownMenuTrigger: FC = ({ children }) => <View>{children}</View>;
export const DropdownMenuContent: FC = ({ children }) => <View>{children}</View>;
export const DropdownMenuItem: FC = ({ children }) => <View>{children}</View>;
export const DropdownMenuLabel: FC = ({ children }) => <View>{children}</View>;
export const DropdownMenuSeparator: FC = () => <View style={{ height: 1, backgroundColor: "#262626" }} />;
export default DropdownMenu;
