export { 
  LineChart,
  Line,
  AreaChart,
  Area,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "./index.web";

export { 
  LineChart as LineChartNative,
  Line as LineNative,
  AreaChart as AreaChartNative,
  Area as AreaNative,
  BarChart as BarChartNative,
  Bar as BarNative,
  PieChart as PieChartNative,
  Pie as PieNative,
  Cell as CellNative,
  XAxis as XAxisNative,
  YAxis as YAxisNative,
  CartesianGrid as CartesianGridNative,
  Tooltip as TooltipNative,
  Legend as LegendNative,
  ResponsiveContainer as ResponsiveContainerNative,
} from "./index.native";
